<?php
/**
 *
 * @category   MageCore
 * @copyright  Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?>
<?php
/** @var $this Itoris_LayeredNavigation_Block_Layer_View */
?>
<?php //echo $this->getStateHtml() ?>
<?php if($this->canShowOptions()): ?>
	<div class="block-subtitle">
		<div>
			<?php if ($this->isStateNotEmpty()) {?>
				<button type="button" onclick="LayNav.sendWithAdditionalParams({clear:'all'})" class="button"><span><span><?php echo $this->__('Clear All') ?></span></span></button>
			<?php } ?>
			<?php echo $this->__('Shopping Options') ?>
		</div>
	</div>

	<dl id="narrow-by-list" class="narrow-by-list">
		<?php $_filters = $this->getFilters() ?>
        <?php foreach ($_filters as $_filter): ?>
            <?php if($_filter->canBeShown()): ?>
                <dt id="laynav-filter-<?php echo $_filter->getFilter()->getRequestVar() ?>" class="<?php echo $_filter->isClosed() ? 'ln-closed' : 'ln-opened' ?>" onclick="LayNav.Toggler.toggle(this, '<?php echo $_filter->getFilter()->getRequestVar() ?>'); ">
                    <?php if ($_filter->hasFiltersInState()) {?>
                        <button class="clear-filter-button" type="button"
                                onclick="LayNav.sendWithAdditionalParams({clear: '<?php echo $_filter->getFilter()->getRequestVar() ?>'});Event.stop(LayNav.evObj(arguments)); return false;" ></button>
                    <?php } ?>
                    <?php echo $this->__($_filter->getName()); ?>
                </dt>
                <dd <?php if ($_filter->isClosed()) { ?>style="display: none;" <?php } ?>><?php echo $_filter->getHtml() ?>
                    <?php if($_filter->getFilter()->getRequestVar()): ?>
                        <script type="text/javascript">
                            var el = jQuery('#laynav-filter-' + '<?php echo $_filter->getFilter()->getRequestVar() ?>').next();
                            hasFiltersInState = <?php echo $_filter->hasFiltersInState() ? 1 : 0 ?>;
                            manNavigationItemsOpen(el, hasFiltersInState);
                        </script>
                    <?php endif; ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
	</dl>
	<script type="text/javascript">decorateDataList('narrow-by-list')</script>
<?php endif; ?>
<?php
	/** @var $state Mage_Catalog_Model_Layer_State */
	$state = $this->getLayer()->getState();
	$enterpriseEngine = $this->getDataHelper()->isEnabledThirdEngineSearch();
	/** @var $filterItem Mage_Catalog_Model_Layer_Filter_Item */
	foreach ($state->getFilters() as $filterItem) {
		//var_dump($filterItem->debug());
		if ($enterpriseEngine) {
			continue;
		}
		if ($filterItem->getOutputInCheckbox()) {
			continue;
		}
		if ($filterItem->getFilter()->getRequestVar() == 'price') {
			continue;
		}
		if ($filterItem->getFilter() instanceof Itoris_LayeredNavigation_Model_Layer_MultiFilter_Decimal) {
			continue;
		}
		?>
			<input type="hidden" name="<?php echo $filterItem->getFilter()->getRequestVar() ?>[<?php echo $filterItem->getRequestVarKey() ?>]"
				   value="<?php echo $filterItem->getValue() ?>" <?php if ($this->getDataHelper()->getNotUseFilter()): ?> class="not-use-in-request"<?php endif; ?>/>

<?php } ?>
<script type="text/javascript">
//<![CDATA[
	LayNav.addObserversToCheckboxes();
//]]>
</script>
