<?php
/**
 * @category    design
 * @package     monster_default
 * @copyright   Copyright (c) 2012 Monster Market. (http://www.monstermarket.com)
 */
?>


<footer class="footer-bottom-container sellyours-footer-container">
    <div class="footer-bottom">
    	<ul>
    		<li><a href="#"><?php echo $this->__('Browse All Products')?></a></li>
    		<li><a href="<?php echo $this->getUrl('udsell/index/sellsearch')?>"><?php echo $this->__('Sell with Us')?></a></li>
    		<li><a href="#"><?php echo $this->__('Help')?></a></li>
    		<li><a href="#"><?php echo $this->__('RSS')?></a></li>
    	</ul>
    	<p class="copyright">&copy; 2012 <?php echo $this->__('Monster Market')?>. <?php echo $this->__('All rights reserved.')?>
    		<span class="pipe">|</span><a href="#"><?php echo $this->__('Privacy Policy')?></a>
    		<span class="pipe">|</span><a href="#"><?php echo $this->__('Terms of Use')?></a>
    	</p>
    </div>
</footer>