<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Forms
 * @version    1.0.5
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Forms_Block_Render_Element_Checkbox $this */
?>
<?php foreach ($this->getOptions() as $option): ?>
<label for="<?php echo $this->getInputId(); ?>-<?php echo $option->getOptionId(); ?>">
    <input type="checkbox"
           class="checkbox <?php echo $this->getInputId(); ?>"
           name="<?php echo $this->getInputName(); ?>"
           id="<?php echo $this->getInputId(); ?>-<?php echo $option->getOptionId(); ?>"
           value="<?php echo $option->getOptionId(); ?>">
    <?php echo $this->escapeHtml($option->getTitle()); ?>
</label>
<br />
<?php endforeach; ?>
<?php if ($this->getEnableOther()): ?>
<label for="<?php echo $this->getInputId(); ?>-other">
    <input type="checkbox"
           class="checkbox <?php echo $this->getInputId(); ?>"
           name="<?php echo $this->getInputName(); ?>"
           id="<?php echo $this->getInputId(); ?>-other"
           value="other">
    <?php echo $this->_helper()->__("Other..."); ?>
</label>
<br />
<script type="text/javascript" >
    if ($('<?php echo $this->getInputId(); ?>-other')){
        $('<?php echo $this->getInputId(); ?>-other').observe('click', function(event){
            if ($('<?php echo $this->getInputId(); ?>-other').checked){
                $('<?php echo $this->getOtherId(); ?>').style.display = 'block';
            } else {
                $('<?php echo $this->getOtherId(); ?>').style.display = 'none';
            }
        });
    }
</script>
<?php endif; ?>
<?php if ($this->getIsRequire()): ?>
<input type="hidden" name="validate-form-checkbox-<?php echo $this->getInputId(); ?>" class="validate-form-checkbox-<?php echo $this->getInputId(); ?>" value="" />
<script type="text/javascript">
        Validation.addAllThese(
        [
            ['validate-form-checkbox-<?php echo $this->getInputId(); ?>', '<?php echo $this->_helper()->__('Please select one of these options') ?>', function(v) {
                var result = false;
                $$('.checkbox.<?php echo $this->getInputId(); ?>').each((function(element){
                    if (element.checked){
                        result = true;
                    }
                }).bind(result));
                return result;
            }]
        ]
        );
</script>
<?php endif; ?>