<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Forms
 * @version    1.0.5
 * @copyright  Copyright (c) 2011-2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
/** @var Magpleasure_Forms_Block_Render_Element_Multioption $this */
?>
<select class="input-text<?php echo $this->getIsRequire() ? " required-entry" : ""; ?>"
       type="text"
       name="<?php echo $this->getInputName(); ?>"
       id="<?php echo $this->getInputId(); ?>"
       value="<?php echo $this->getValue(); ?>">
    <option></option>
    <?php foreach ($this->getOptions() as $option): ?>
    <option value="<?php echo $option->getOptionId(); ?>"><?php echo $option->getTitle(); ?></option>
    <?php endforeach; ?>
    <?php if ($this->getEnableOther()): ?>
    <option value="other"><?php echo $this->_helper()->__("Other..."); ?></option>
    <?php endif; ?>
</select>
<?php if ($this->getEnableOther()): ?>
<script type="text/javascript">
    $('<?php echo $this->getInputId(); ?>').observe('change', function(event){
        if ($('<?php echo $this->getInputId(); ?>') && $('<?php echo $this->getOtherId(); ?>')){
            if ($('<?php echo $this->getInputId(); ?>').value == 'other'){
                $('<?php echo $this->getOtherId(); ?>').style.display = 'block';
            } else {
                $('<?php echo $this->getOtherId(); ?>').style.display = 'none';
            }
        }
    });
</script>
<?php endif; ?>