<?php
/**
 *
 * @category   MageCore
 * @copyright  Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('info');?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<div class="data-table-holder">
    <div class="data-table" id="my-orders-table">
        <div class="thead">
            <div class="tr-col">
                <div class="th-col"><?php echo $this->__('Order #') ?></div>
                <div class="th-col"><?php echo $this->__('Date') ?></div>
                <div class="th-col col-ship"><?php echo $this->__('Ship To') ?></div>
                <div class="th-col"><span class="nobr"><?php echo $this->__('Order Total') ?></span></div>
                <div class="th-col col-status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></div>
                <div class="th-col">&nbsp;</div>
            </div>
        </div>
        <div class="tbody">
            <?php $_odd = ''; ?>
            <?php foreach ($_orders as $_order): ?>
            <div class="tr-col">
                <div class="td-col"><?php echo $_order->getRealOrderId() ?></div>
                <div class="td-col"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></div>
                <div class="td-col col-ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></div>
                <div class="td-col"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></div>
                <div class="td-col col-status"><em><?php echo $_order->getStatusLabel() ?></em></div>
                <div class="td-col">
                    <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View') ?></a>
                        <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                        <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                    </span>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
