<?php
/**
 * @category   MageCore
 * @package    enterprise_jewelersclub
 * @copyright  Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?>
<?php
/** @var $this Itoris_LayeredNavigation_Block_Layer_MultiFilter_Category_Tree */
/** @var $_helper Oro_LayeredNavigation_Helper_Data */
?>
<?php $_helper = $this->helper('oro_layerednavigation'); ?>
<ol class="ln-tree <?php echo (count($this->getItems()) > $_helper->getFilterNavigationItemsCount()) ? 'category-accordion-filter' : '' ?>">
<?php foreach($this->getItems() as $_item) { ?>
	<?php /** @var $_item Mage_Catalog_Model_Category */
		if ($_item->getProductCount() <= 0) {
			continue;
		}
	?>
    <li>
		<input type="checkbox" class="itoris_laynav_checkbox" id="item_<?php echo $_item->getEntityId() ?>"
			   <?php if ($_item->getInState()) { ?> checked="checked" <?php } ?>
			   name="<?php echo $_item->getFilter()->getRequestVar() ?>[]" value="<?php echo $_item->getEntityId() ?>" />
		<label><a <?php if ($_item->getIsAnchor()) { ?> onclick="LayNav.categoryClick(this); return false;" <?php } ?> href="<?php echo $_item->getUrl() ?>"><?php echo $_item->getName() ?></a></label>
        (<?php echo $_item->getProductCount() ?>)
		<?php echo $this->getLayerHtml($_item); ?>
    </li>
<?php } ?>
</ol>
