<?php
/**
 * {magecore_license_notice}
 *
 * @category   design
 * @package    enterprise_default
 * @copyright  {magecore_copyright}
 * @license    {magecore_license}
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_imageSize = 200;
    $_smallImageSize = 68;
?>
<p class="product-image" id="popup-image-<?php echo $_product->getId(); ?>-0">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_imageSize).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>

<?php if (count($this->getGalleryImages()) > 0): ?>
<?php foreach ($this->getGalleryImages() as $_image): ?>
    <p class="product-image" id="popup-image-<?php echo $_product->getId(); ?>-<?php echo $_image->getValueId() ?>" style="display:none">
        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_imageSize); ?>" width="<?php echo $_imageSize ?>" height="<?php echo $_imageSize ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </p>
<?php endforeach; ?>

<div class="more-views">
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="javascript:void(0);" id="popup-gallery-<?php echo $_product->getId(); ?>-<?php echo $_image->getValueId() ?>" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_smallImageSize); ?>" width="<?php echo $_smallImageSize ?>" height="<?php echo $_smallImageSize ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
