<?php
/**
 * {magecore_license_notice}
 *
 * @category   Oro
 * @package    Oro_ProductQuickView
 * @copyright  {magecore_copyright}
 * @license    {magecore_license}
 */
?>
<?php $_product = $this->getProduct() ?>
<div class="social-hold">
<a href="//www.pinterest.com/pin/create/button/?url=<?php echo urlencode($_product->getProductUrl()) ?>&media=<?php echo Mage::helper('catalog/image')->init($_product, 'image') ?>&description=<?php echo urlencode($_product->getName()) ?>" data-pin-do="buttonPin" data-pin-config="above"><img src="<?php echo $this->getSkinUrl('images/pinit.png') ?>" /></a>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $_product->getProductUrl(); ?>" data-text="<?php echo $_product->getName()?>">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>
<div class="iframe-holder">
    <iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode($_product->getProductUrl()); ?>&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px; width: 110px; float: left;" allowTransparency="true"></iframe>
</div>
