<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container" id="header">
    <div class="header-panel">
        <div class="switches"><?php echo $this->getChildHtml('switches') ?></div>
        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?></p>
        <?php echo $this->getChildHtml('accountLinks') ?>
    </div>
    <div class="header">
        <div class="branding">
            <?php if ($this->getIsHomePage()):?>
                <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo Mage::getStoreConfig("web/unsecure/base_url"); ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
                <a href="<?php echo Mage::getStoreConfig("web/unsecure/base_url"); ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
            <?php echo $this->getChildHtml('headerCallout') ?>
        </div>
        <div class="quick-access">
            <div class="social-plugin">
                <div class="social-hold">
                <a href="//www.pinterest.com/pin/create/button/?url=<?php echo urlencode(Mage::getStoreConfig("web/unsecure/base_url")) ?>&media=<?php echo $this->getLogoSrc() ?>&description=<?php echo urlencode($this->getLogoAlt()) ?>" data-pin-do="buttonPin" data-pin-config="beside"><img src="<?php echo $this->getSkinUrl('images/pinit.png') ?>" /></a>
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo Mage::getStoreConfig("web/unsecure/base_url") ?>" data-text="<?php echo $this->getLogoAlt() ?>">Tweet</a>
                </div>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                <div class="iframe-holder">
                    <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fjclubmarketplace&amp;width=110&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21&amp;appId=1525766614371796" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:110px; height:21px;" allowTransparency="true"></iframe>
                </div>
            </div>
            <div class="header-holder">
                <div class="header-frame">
                    <?php echo $this->getChildHtml('topCart') ?>
                    <div class="top-nav">
                        <div class="email-top dropdown-extra">
                            <span class="dropdown-opener" ><?php echo $this->__('Email') ?></span>
                            <div class="block-email dropdown-content">
                                <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
                                    <div class="form-subscribe">
                                        <div class="form-subscribe-header">
                                            <label for="newsletter"><?php echo $this->__('Sign up to receive upcoming events & Deals') ?></label>
                                        </div>
                                        <input name="email" type="text" id="newsletter" value="<?php echo $this->__('') ?>" onclick="this.value=='<?php echo $this->__('Enter your email address') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Enter your email address') ?>':''" class="input-text required-entry validate-email" />
                                        <button type="submit" class="button" title="<?php echo $this->__('Subscribe') ?>"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
                                        <span class="description"><?php echo $this->__('Unsubscribe any time.') ?></span>
                                    </div>
                                </form>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
                                    //]]>
                                </script>
                            </div>
                        </div>
                        <div class="links-holder slide">
                            <a class="opener-mobile" href="#">opener</a>
                            <?php echo $this->getChildHtml('topLinks') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('topSearch') ?>
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topContainer') ?>
</div>
