<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>

<div class="top-cart">
<?php $_cartQty = $this->getSummaryCount() ?>
<?php if ($_cartQty > 0): ?>
    <?php $_myCart = $this->__('<em>Shopping Bag:</em> %s', '<span>' . $_cartQty . '</span>') ?>
<?php else: ?>
    <?php $_myCart = $this->__('<em>Shopping Bag:</em> %s', '<span>0</span>') ?>
<?php endif ?>
<?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()):?>
    <div class="block-title no-items">
        <ul class="links cart-link">
            <li ><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $_myCart ?></a></li>
        </ul>
    </div>
<?php else:?>
    <div class="block-title<?php if(!$_cartQty) { echo (' no-items'); } ?>">
        <strong id="cartHeader"><?php echo $_myCart ?></strong>
    </div>
    <div id="topCartContent" class="block-content" style="display:none">
        <div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown ?>
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>
            <?php /* ?>
                <p class="block-subtitle">
                    <span onclick="Enterprise.TopCart.hideCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
                    <?php echo $this->__('Recently added item(s)') ?>
                </p>
            <?php */ ?>
            <ol id="mini-cart" class="mini-products-list">
            <?php foreach($_items as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
        <?php else: ?>
            <?php /* ?>
                <p class="block-subtitle">
                    <span onclick="Enterprise.TopCart.hideCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
                    <?php echo $this->__('Recently added item(s)') ?>
                </p>
             <?php */ ?>
            <p class="cart-empty">
                <?php echo $this->__('You have no items in your shopping cart.') ?>
            </p>
            <?php if ($this->getCartEmptyMessage()): ?>
                <p class="cart-empty cart-empty-message"><?php echo $this->getCartEmptyMessage(); ?></p>
            <?php endif; ?>
        <?php endif ?>
        <?php if ($_cartQty || $this->getAllowCartLink()): ?>
            <?php $isPossibleOnepageCheckout = $_cartQty && $this->isPossibleOnepageCheckout() ?>
            <?php if ($isPossibleOnepageCheckout): ?>
                <div class="holder">
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                            <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                            <span class="label"><?php echo $this->__('Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?><?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?> / <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?><?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <a class="view-cart" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('View Cart') ?></span></a>
                </div>
            <?php endif ?>
            <div class="actions">
                <?php if ($isPossibleOnepageCheckout): ?>
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout now') ?></span></span></button>
                <?php endif ?>
            </div>
        <?php endif ?>
        </div>
    </div>
<script type="text/javascript">
    var tc = function(){};
    tc.prototype = Enterprise.TopCart;
    tc.prototype.clickHandler = function(event){
        if (!$(this.elementHeader).hasClassName('expanded') && !$(this.container.id).hasClassName('process'))  {
            return;
        }
        var el = $(this.container.id);
        var vp = el.viewportOffset();
        var layout = el.getLayout();
        var width = layout.get('width');
        var height = layout.get('height');

        if(event.clientX < vp.left || event.clientX > vp.left + width || event.clientY < vp.top || event.clientY > vp.top + height){
            setTimeout(this.hideCart.bind(this), 10);
            console.log(this.openedPopup);
        }
    };
    tc.prototype.handleMouseClick = function (evt) {
        if (!$(this.elementHeader).hasClassName('expanded') && !$(this.container.id).hasClassName('process'))  {
            setTimeout(this.showCart.bind(this), 10);
        }
        else {
            this.hideCart();
        }
    };

    tc.prototype.handleMouseClick = function (evt) {
        if (!$(this.elementHeader).hasClassName('expanded') && !$(this.container.id).hasClassName('process'))  {
            setTimeout(this.showCart.bind(this), 10);
        }
        else {
            this.hideCart();
        }
    };

    var t = new tc();
    t.initialize('topCartContent');

    // Below can be used to show minicart after item added
    // Enterprise.TopCart.showCart(7);

    document.observe("click", function(event){
        t.clickHandler(event);
    });

    document.observe('keyup', function(event){
        t.hideCart();
    });
</script>
<?php endif;?>
</div>
