<?php
/**
 * template for earn points output
 *
 * @category MageCore
 * @package Oro_Onsale
 * @copyright Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
Mage::helper('udmultiprice')->attachPriceComparisonByState($_productCollection);
$vendors = Mage::helper('udmulti/data')->getMultiVendorData($_productCollection, true, true);
$pVendor = array();
foreach($vendors as $vendor){
    $vId = $vendor->getProductId();
    if($pVendor[$vId] == null){
        $pVendor[$vId] = array();
    }
    if($vendor->getVendorName() != "Local Vendor"){
        $pVendor[$vId][] = $vendor;
    }
}
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product):
                    $priceCmp = $_product->getData('PriceComparisonByState');
                    $priceCmpCnt = $_product->getData('PriceComparisonByStateCnt');
                    $priceCmpStates = $_product->getData('PriceComparisonCanonicStates');
                    ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
                                <div class="price-box">
                                    <?php if (is_array($priceCmp) && !empty($priceCmp)): foreach ($priceCmp as $pCmpState=>$pCmp): ?>
                                        <p class="<?php echo @$priceCmpStates[$pCmpState]['html_value']?>-price">
                                            <span class="price-label"><?php echo Mage::helper('udmultiprice')->__('%s %s from', @$priceCmpCnt[$pCmpState]*1, @$priceCmpStates[$pCmpState]['html_label'])?></span>
                                            <span class="price"><strong><?php echo $this->helper('core')->formatPrice(@$pCmp[0])?></strong></span>
                                        </p>
                                    <?php endforeach; ?>
                                    <?php else: ?>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php endif; ?>
                                </div>
                                <?php if($_product->isSaleable()): ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid">
                <?php $i=0; foreach ($_productCollection as $_product):
                    $priceCmp = $_product->getData('PriceComparisonByState');
                    $priceCmpCnt = $_product->getData('PriceComparisonByStateCnt');
                    $priceCmpStates = $_product->getData('PriceComparisonCanonicStates');
                    ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <div class="image-holder onsale-category-container-grid">
                            <div class="image-hold">
                                <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            </div>
                            <?php if(($popupBlock = $this->getChild('oro_productquickview_popup')) != null):?>
                                <?php echo $popupBlock->setProduct($_product)->toHtml() ?>
                            <?php endif ?>
                        </div>
                        <div class="product-container">
                            <h2 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo '...'.$this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $this->helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getName(), 'name'), 75) ?>
                                </a>
                            </h2>
                            <div class="rating-holder">
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                <div class="price-box">
                                    <?php if (is_array($priceCmp) && !empty($priceCmp)): foreach ($priceCmp as $pCmpState=>$pCmp): ?>
                                        <p class="<?php echo @$priceCmpStates[$pCmpState]['html_value']?>-price">
                                            <span class="price-label"><?php echo Mage::helper('udmultiprice')->__('%s %s from', @$priceCmpCnt[$pCmpState]*1, @$priceCmpStates[$pCmpState]['html_label'])?></span>
                                            <span class="price"><strong><?php echo $this->helper('core')->formatPrice(@$pCmp[0])?></strong></span>
                                        </p>
                                    <?php endforeach; ?>
                                    <?php else: ?>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php $this->setProduct($_product) ?>
                            <?php echo $this->getChildHtml('earn_points', false) ?>
                            <?php $v = isset($pVendor[$_product->getId()]) ? $pVendor[$_product->getId()] : array(); ?>

                            <?php if(count($v) > 0): ?>
                                <div class="sold">
                                    <?php echo $this->__('Sold By') ?>
                                    <?php foreach($v as $vendor):?>
                                        <?php $v = Mage::helper('udropship/data')->getVendor($vendor->getVendorName());?>
                                        <a href="<?php echo Mage::helper('umicrosite/data')->getVendorUrl($v)?>"><?php echo $vendor->getVendorName(); ?></a>
                                    <?php endforeach ?>
                                </div>
                            <?php endif ?>
                            <!--div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div-->
                        </div>
                    </li>
                    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                <?php endif ?>
                <?php endforeach ?>
            </ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
