<?php /** @var $this Oro_FeaturedProducts_Block_List */ ?>
<?php
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="featured-products">
        <h2>featured products</h2>
        <div class="gallery-holder">
            <a id="prev-featured" class="prev" href="#"><?php echo $this->__('prev') ?></a>
            <a id="next-featured" class="next" href="#"><?php echo $this->__('next') ?></a>
            <div class="list_carousel">
                <ul class="products-grid" id="featured-products">
                    <?php foreach ($_productCollection as $_product): ?>
                        <li class="item">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(166); ?>" width="166" height="166" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            <div class="hold">
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short', true) ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                            <?php echo Mage::helper('oro_earnpoints')->getRateHtml($_product); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    jQuery(document).ready(function() {
        function carousellResize(){
            if(jQuery(window).width() > 767){
                carousellMe('left')
            }else{
                carousellMe('center')
            }
        }
        function carousellMe(alignMe){
            jQuery('#featured-products').carouFredSel({
                items :'variable',
                width : "100%",
                align: alignMe,
                circular: true,
                infinite: false,
                prev: '#prev-featured',
                next: '#next-featured',
                mousewheel: true,
                auto:{
                    play: true,
                    timeoutDuration : 5000
                },
                swipe: {
                    onMouse: true,
                    onTouch: true
                }
            });
        }
        if(jQuery('#featured-products').length > 0){
            carousellResize();
            jQuery(window).resize(function(){
                carousellResize();
            });
        }
    });
</script>
