<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->setEscapeMessageFlag(true)->toHtml() ?></div>
<div class="product-view">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-essential">
            <div class="product-img-box">
                <div class="product-img-holder">
                    <?php echo $this->getChildHtml('media') ?>
                </div>
            </div>

            <div class="product-shop">
                <div class="product-main-info">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                    <?php /*?>
                        <p class="product-ids"><?php echo $this->__('SKU# %s', $this->escapeHtml($_product->getSku())); ?></p>
                    <?php */ ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container2') ):?>
                        <div class="options-container-big">
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        </div>
                    <?php endif;?>
                </div>
                <?php echo ($_product->getCanShowPrice() === false) ? '' : $this->getChildHtml('tierprices'); ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php ?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>

                    </div>
                <?php else: ?>
                    <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container1') ):?>
                        <div class="options-container-small">
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        </div>
                    <?php else: ?>

                    <?php endif;?>
                <?php endif; ?>
                <?php /*?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                </div>
                <?php */?>

                <div class="buttons-hold">
                <?php echo $this->getChildHtml('addto') ?>
                <?php if ($this->canEmailToFriend()): ?>
                    <p class="emailto-link"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><span></span><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
                </div>
                <?php if ($_product->getShortDescription()):?>
                    <?php /* ?>
                    <div class="short-description std">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                    </div>
                    <?php */ ?>
                <?php endif;?>


                <div class="plugin">
                    <!-- AddThis Button BEGIN -->
                    <div class="addthis_toolbox addthis_default_style">
                        <a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal" pi:pinit:url="http://www.addthis.com/features/pinterest" pi:pinit:media="http://www.addthis.com/cms-content/images/features/pinterest-lg.png"></a>
                        <a class="addthis_button_tweet"></a>
                        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                    </div>
                    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-52d67b5d4ba75e84"></script>
                    <!-- AddThis Button END -->
                </div>
            </div>
        </div>
        <div class="product-collateral">
            <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                <dl id="collateral-tabs" class="collateral-tabs">
                <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                    <dd class="tab-container">
                       <div class="tab-content"><?php echo $html ?></div>
                    </dd>
                <?php endforeach;?>
                </dl>
                <script type="text/javascript">
                //<![CDATA[
                    var collateralTabs = new Enterprise.Tabs('collateral-tabs');
                    Event.observe(window, 'load', function() {
                        collateralTabs.select();
                    });
                //]]>
                </script>
            <?php endif; ?>
        </div>
        <div class="clearer"></div>

    </form>
        <?php /* ?>
            <?php echo $this->getChildHtml('relatedProducts') ?>

        <?php echo $this->getChildHtml('upsell_products') ?>
            <?php echo $this->getChildHtml('productTagList') ?>
         <?php */ ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
</div>

<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>
<?php echo $this->getChildHtml('reports.product.viewed') ?>