<?php
/**
 *
 * @category   MageCore
 * @copyright  Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink">
    </span>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

