<?php
/**
 * Video Plugin for Magento
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Niveus
 * @package    Niveus_ProductVideo
 * @copyright  Copyright (c) 2013 Niveus Solutions (http://www.niveussolutions.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Niveus Solutions <support@niveussolutions.com>
 */
?>
<?php /*
    $_productVideos = $this->_getProductVideos();
?>
<?php if(!empty($_productVideos)):?>
    <h3><?php echo $this->__('Product Videos') ?></h3>
    <div class="videos-wrap">
    <?php foreach($_productVideos as $videoLink) : ?>
        <?php //$video = $this->getCode($video);?>
        <?php $videoCode = $this->getVideoCode($videoLink); ?>
        <?php if($videoCode !=''):?>
            <div class="product-videos">
                <?php echo "<iframe width=\"560\" height=\"315\" src=\"http://www.youtube.com/embed/" . $this->escapeHtml($videoCode) . "\" frameborder=\"0\"></iframe>";?>
            </div>
        <?php endif;?>               
    <?php endforeach; ?>
    </div>
<?php endif;*/?>
<!--script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function() {
    jQuery('.product-videos').fitVids();
});
//]]>
</script-->