<?php
/**
 *
 * @category   MageCore
 * @copyright  Copyright (c) 2014 Oro Inc. DBA MageCore (http://www.magecore.com)
 */
?><?php
?>
<label for="email_an" class="an-data"><?php echo $this->__('Get access to exclusive online deals') ?></label>
<?php if ($this->displayEmail()): ?>

    <div class="v-fix">
        <input name="email" type="text" id="email_an" class="an-data validate-email required-entry" value="Enter your email" />
    </div>
<?php endif; ?>
<?php if ($this->displaySalutation()): ?>
    <?php 
    $selected0 = $selected1 = '';
    $this->getSubscriber()->getSalutation() == 1 ? $selected1 = 'selected="selected"' : $selected0 = 'selected="selected"';
        ?>
    <label for="salutation_an" class="an-data"><?php echo $this->__('Salutation') ?><span class="required">*</span></label>
    <select name="salutation" id="salutation_an" class="an-data required-entry">
        <option <?php echo $selected0 ?> value="0"><?php echo Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::SALUTATION_FIRST) ?></option>
        <option <?php echo $selected1 ?> value="1"><?php echo Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::SALUTATION_SECOND) ?></option>
    </select>
<?php endif; ?>
<?php if ($this->displayNames()): ?>
    <label for="firstname_an" class="an-data"><?php echo $this->__('First name') ?><span class="required">*</span></label>
    <input name="first_name" type="text" id="firstname_an" class="an-data required-entry"/>
    <label for="lastname_an" class="an-data"><?php echo $this->__('Last name') ?><span class="required">*</span></label>
    <input name="last_name" type="text" id="lastname_an" class="an-data required-entry"/>
<?php endif; ?>
<?php if($this->displayPhone()): ?>
    <label for="phone_an" class="an-data"><?php echo $this->__('Phone') ?><span class="required">*</span></label>
    <input name="phone" type="text" id="phone_an" class="an-data required-entry" value="<?php echo $this->getSubscriber()->getPhone() ?>" />
<?php endif; ?>