<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento enterprise edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento enterprise edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.3.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php $this->setBlockUniqueId($this->getBlockUniqueId() + 1) ?>
<div class="form-subscribe an-subscribe">
    <div class="block-content">
        <div class="an-buttons">
            <button id="advancednewsletter-button-<?php echo $this->getBlockUniqueId() ?>" type="submit" class="button">
                <span><span><?php echo $this->__('Subscribe') ?></span></span>
            </button>
        </div>
    </div>
</div>

<script type="text/javascript">
    <!--
    Event.observe(window, 'load', function () {
        new Advancednewsletter($('advancednewsletter-button-<?php echo $this->getBlockUniqueId() ?>'), '<?php echo $this->getAjaxUrl() ?>');
    });
    //-->
</script>
