<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$_nativeZoom = false;
$_imageSize = 370;
?>


<?php if (!$_nativeZoom): ?>
    <?php /* --------- jqZoom --------- */ ?>
    <div class="product-image-frame onsale-product-container">
        <div id="image-wrap" class="product-image-wrap">
            <?php echo Mage::helper('onsale')->getProductLabelHtml($_product); ?>
            <a id="zoom-container" rel="product-gallery" class="jqzoom" id="popup-image-<?php echo $_product->getId(); ?>-0" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')?>">
                <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_imageSize).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </a>
            <script type="text/javascript">
                jQuery(document).ready(function(){
                    jQuery('a#zoom-container').jqzoom({
                        zoomType:"innerzoom",
                        preloadImages:true,
                        title: false
                    });
                })
            </script>

            <?php if($_product->getYoutubeVideoOne() || $_product->getYoutubeVideoTwo() || $_product->getYoutubeVideoThree()): ?>
                <div class="youtube-video">
                    <p class="product-image" id="popup-image-<?php echo $_product->getId(); ?>" style="display: none">
                    </p>
                </div>
            <?php endif ?>
        </div>
    </div>

<?php else: ?>

    <?php /* --------- native magento zoom --------- */ ?>

    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <?php
            $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="track">
                <div id="handle"></div>
            </div>
            <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
        <script type="text/javascript">
            //<![CDATA[
            Event.observe(window, 'load', function() {
                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
            });
            //]]>
        </script>
    <?php else: ?>
        <p class="product-image">
            <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(275).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>

    <?php /* --------- /native magento zoom --------- */ ?>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0 || $_product->getYoutubeVideoOne()): ?>
    <div class="more-views">
        <ul>
            <?php foreach ($_product->getMediaGalleryImages() as $_image): ?>
                <li>
                    <a rel="{gallery:'product-gallery',smallimage:'<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_imageSize) ?>',largeimage:'<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) ?>'}" href="javascript:void(0)" id="popup-gallery-<?php echo $_product->getId(); ?>-<?php echo $_image->getValueId() ?>" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(48); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </a>
                </li>
            <?php endforeach; ?>
            <?php if($_product->getYoutubeVideoOne()): ?>
                <?php $videoCode = substr(trim(strval($_product->getYoutubeVideoOne())), -11, 11)?>
                <li class="video">
                    <a href="javascript:void(0)" isvideo="1" id="popup-gallery-<?php echo $_product->getId(); ?>-<?php echo $videoCode ?>"><img src="http://img.youtube.com/vi/<?php echo $videoCode?>/0.jpg" width="48" height="48" alt="" /></a>
                </li>
            <?php endif ?>
            <?php if($_product->getYoutubeVideoTwo()): ?>
                <?php $videoCode = substr(trim(strval($_product->getYoutubeVideoTwo())), -11, 11)?>
                <li class="video">
                    <a href="javascript:void(0)" isvideo="1" id="popup-gallery-<?php echo $_product->getId(); ?>-<?php echo $videoCode ?>"><img src="http://img.youtube.com/vi/<?php echo $videoCode?>/0.jpg" width="48" height="48" alt="" /></a>
                </li>
            <?php endif ?>
            <?php if($_product->getYoutubeVideoThree()): ?>
                <?php $videoCode = substr(trim(strval($_product->getYoutubeVideoThree())), -11, 11)?>
                <li class="video">
                    <a href="javascript:void(0)" isvideo="1" id="popup-gallery-<?php echo $_product->getId(); ?>-<?php echo $videoCode ?>"><img src="http://img.youtube.com/vi/<?php echo $videoCode?>/0.jpg" width="48" height="48" alt="" /></a>
                </li>
            <?php endif ?>
        </ul>
    </div>
<?php endif; ?>
