<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable()): ?>
        <a href="<?php echo $this->getRssLink() ?>" title="<?php echo $this->__('Subscribe to RSS Feed') ?>" class="rss-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $this->getCurrentCategory()->getName(), 'name') ?></h1>
</div>

<div class="section-category-first-part">
    <?php echo $this->getChildHtml('advslider'); ?>
    <?php echo $this->getChildHtml('subcategories') ?>

    <div class="button-view-all">
        <span class="opener-view-all" >View all products</span>
    </div>
    <?php echo $this->getChildHtml('topsellers'); ?>
</div>
<div class="section-category-second-part" style="display: none;">

    <?php echo $this->getChildHtml('subcategories') ?>

    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="category-view">
        <?php /* ?>
            <?php if($_imgUrl): ?>
                <?php echo $_imgHtml ?>
            <?php endif; ?>
         <?php */ ?>
        <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
            <div class="category-description std">
                <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
            </div>
        <?php endif; ?>

        <?php if($this->isContentMode()): ?>
            <?php echo $this->getCmsBlockHtml() ?>

        <?php elseif($this->isMixedMode()): ?>
            <?php echo $this->getCmsBlockHtml() ?>
            <?php echo $this->getProductListHtml() ?>

        <?php else: ?>
            <?php echo $this->getProductListHtml() ?>
        <?php endif; ?>
    </div>
</div>

