<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-title title-buttons address-title">
    <h1><?php echo $this->__('Address Book') ?></h1>
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button button-address" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><em>+</em> <?php echo $this->__('Add New Address') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo $this->__('Default Billing Address') ?> </h3>
                <address class="box-content">
                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <a class="change" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change') ?></a>
           </li>
        <?php else: ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo $this->__('Default Billing Address') ?></h3>
                <p class="box-content"><?php echo $this->__('You have no default billing address in your address book.') ?></p>
            </li>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo $this->__('Default Shipping Address') ?></h3>
                <address class="box-content">
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <a class="change" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change') ?></a>
            </li>
        <?php else: ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo $this->__('Default Shipping Address') ?></h3>
                <p class="box-content"><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
    <div class="col-2 addresses-additional">
        <h2 class="sub-title"><?php echo $this->__('More Addresses') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?><br />
                </address>
                <p class="actions">
                    <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit') ?></a>
                    <span class="separator">|</span>
                    <a class="remove-link" href="#" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Remove') ?></a>
                </p>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
