<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if( $this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
        <div class="data-table-holder">
            <div class="data-table" id="my-reviews-table">
                <div class="tbody">
                    <?php foreach ($this->getCollection() as $_review): ?>
                    <div class="tr-col">
                        <div class="td-col date-td"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></div>
                        <div class="td-col"><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h2></div>
                        <div class="td-col">
                        <?php if($_review->getSum()): ?>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                            </div>
                        <?php endif; ?>
                        </div>
                        <div class="td-col"><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></div>
                        <div class="td-col"><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>"><?php echo $this->__('View Details') ?></a></div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <script type="text/javascript">decorateTable('my-reviews-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
