<?php
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
    <div class="block block-list block-viewed">
        <div class="block-title">
            <strong><span><?php echo $this->__('You Recently Viewed') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $_columnCount = $this->getColumnCount(); ?>

            <div class="gallery-holder">
                <a id="prev-viewed" class="prev" href="#"><?php echo $this->__('prev') ?></a>
                <a id="next-viewed" class="next" href="#"><?php echo $this->__('next') ?></a>
                <div class="list_carousel">
                    <ul id="recently-viewed-items">
                        <?php $i=0; foreach ($_products as $_product): ?>
                            <li class="item">
                                <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" /></a>
                                <h2><?php echo $this->stripTags($_product->getName(), null, true) ?></h2>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short', true)?>
                                <div class="price-box">
                                    <span class="regular-price"><span class="price"><?php echo $this->getPriceHtml($_product, false, null) ?></span></span>
                                </div>
                                <?php echo $this->getChildHtml('extrahint') ?>
                                <?php $this->setProduct($_product) ?>
                                <?php echo $this->getChildHtml('earn_points', false) ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>

            <script type="text/javascript">decorateList('recently-viewed-items');</script>
            <script type="text/javascript">
                jQuery(document).ready(function() {
                    function carousellResize(){
                        if(jQuery(window).width() > 767){
                            carousellMe('left')
                        }else{
                            carousellMe('center')
                        }
                    }
                    function carousellMe(alignMe){
                        jQuery('#recently-viewed-items').carouFredSel({
                            items :'variable',
                            width : "100%",
                            align: alignMe,
                            circular: true,
                            infinite: false,
                            prev: '#prev-featured',
                            next: '#next-featured',
                            mousewheel: true,
                            auto:{
                                play: true,
                                timeoutDuration : 5000
                            },
                            swipe: {
                                onMouse: true,
                                onTouch: true
                            }
                        });
                    }
                    if(jQuery('#recently-viewed-items').length > 0){
                        carousellResize();
                        jQuery(window).resize(function(){
                            carousellResize();
                        });
                    }
                });
            </script>
        </div>
    </div>
<?php endif; ?>