<?php
/**
 * Onepage checkout template
 *
 */
?>
<div class="opc-wrapper">
    <div class="page-title">
        <?php echo $this->getChildHtml('cart_help') ?>
        <?php echo $this->getChildHtml('checkoutCallout') ?>
        <h1><?php echo $this->__('Checkout') ?></h1>
    </div>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
    <div class="shopping-cart-wrap">
        <div class="opc-holder">
            <ol class="opc" id="checkoutSteps">
                <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
                    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
                    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                        <div class="step-title">
                            <span class="number"><?php echo $i ?>.</span>
                            <h2><?php echo $_stepInfo['label'] ?></h2>
                            <a href="#"><?php echo $this->__('Edit') ?></a>
                        </div>
                        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                            <?php echo $this->getChildHtml($_stepId) ?>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
            <div class="mobile-contact">
                <strong><?php echo $this->__('Have Questions? ') ?></strong>
                <p><?php echo $this->__('Contact our Customer Care:') ?> </p>
                <p><?php echo $this->__('(800) 423-7500') ?></p>
                <p> <?php echo $this->__('or') ?> <a href="mailto:customercare@jewelerclub.com"><?php echo $this->__('customercare@jewelerclub.com') ?></a></p>
            </div>
        </div>
        <div class="opc-progress-container" id="col-right-opcheckout">
            <?php echo $this->getChildHtml('checkoutProgress') ?>
            <!-- (c) 2005, 2014. Authorize.Net is a registered trademark of CyberSource Corporation -->
            <div class="AuthorizeNetSeal">
                <script type="text/javascript" language="javascript">var ANS_customer_id="048939ce-90d5-4612-bc91-7b5b5ce8b3ea";</script>
                <script type="text/javascript" language="javascript" src="//verify.authorize.net/anetseal/seal.js" ></script>
                <a href="http://www.authorize.net/" id="AuthorizeNetText" target="_blank">Electronic Check Processing</a>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var accordion = new Accordion('checkoutSteps', '.step-title', true);
        <?php if($this->getActiveStep()): ?>
        accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
        <?php endif ?>
        var checkout = new Checkout(accordion,{
                progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
                review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
                saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
                failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
        );
        //]]>
    </script>
</div>