<?php
/**
 * @category   Oro
 * @package    Oro_GoogleTrustedStore
 */
?>
<?php
    $currentOrderId = Mage::registry('current_order') ? Mage::registry('current_order')->getId() : null;
?>
<script type="text/javascript">
//<![CDATA[

var CancelConfirmation = function () {
    var confirmationPopupHtml = <?php echo Mage::helper('core')->jsonEncode($this->getChild('form')->toHtml()) ?>;
    var cancelTitle = '<?php echo $this->jsQuoteEscape($this->__('Are you sure to cancel order?')) ?>';
    var editTitle = '<?php echo $this->jsQuoteEscape($this->__('Are you sure? This order will be canceled and a new one will be created instead.')) ?>';

    this.open = function(reason) {
        this.overlayShowEffectOptions = Windows.overlayShowEffectOptions;
        this.overlayHideEffectOptions = Windows.overlayHideEffectOptions;
        Windows.overlayShowEffectOptions = {duration:0};
        Windows.overlayHideEffectOptions = {duration:0};

        Dialog.confirm(confirmationPopupHtml, {
            draggable: true,
            resizable: true,
            closable:  true,
            className: 'magento',
            windowClassName: 'popup-window',
            title: (reason == 'edit') ? editTitle : cancelTitle,
            width: 550,
            height: 100,
            zIndex: 1000,
            recenterAuto: false,
            hideEffect: Element.hide,
            showEffect: Element.show,
            id: "catalog-wysiwyg-editor",
            buttonClass: "form-button",
            okLabel: '<?php echo $this->jsQuoteEscape($this->__('OK')) ?>',
            cancelLabel: '<?php echo $this->jsQuoteEscape($this->__('Cancel')) ?>',
            ok: function () {
                var action;
                if (reason == 'edit') {
                    action = <?php
                        echo Mage::helper('core')->jsonEncode(
                            $this->getUrl('*/sales_order_edit/start', array('order_id' => $currentOrderId))
                        );
                    ?>;
                } else {
                    action = <?php
                        echo Mage::helper('core')->jsonEncode(
                            $this->getUrl('*/*/cancel', array('order_id' => $currentOrderId))
                        );
                    ?>;
                }

                window.location =  action + '?cancellation_reason=' + escape($('order_cancellation_reason').getValue());
            }
        });
    }
};

var cancelConfirmationWindow = new CancelConfirmation;

//]]>
</script>

<style type="text/css">
    #catalog-wysiwyg-editor_content .magento_message {padding-top: 10px}
</style>

